version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/zaobao

jobs:
  yarn-build:
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint:md
      - run: yarn lint:js
      - run: yarn test
      - run: yarn test:coverage
    branches:
      only:
        - master
