version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout

      - restore_cache:
        key: node-modules-{{ checksum "yarn.json" }}

      - run:
        name: Install Dependencies
        command: yarn --frozen-lockfile

      - save_cache:
        key: node-modules-{{ checksum "yarn.lock" }}
        paths:
          - ./node_modules
          - ~/.cache/yarn

      - run:
        name: Run Build
        command: yarn build

      - run:
        name: Lint Mardkwon
        command: yarn lint:md

      - run:
        name: Lint JavaScript
        command: yarn lint:js

      - run:
        name: Run Test
        command: yarn test
workflows:
  version: 2
  build-test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
