version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: sudo npm install -g yarn
      - run: yarn install --no-lockfile
      - run: yarn lint:md
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
